# Goal: to build CI/CD pipeline (dummi).
name: CICD demo

on: 
  push:
 
jobs:
  # CI
  code:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone the code
        uses: actions/checkout@v7
  
  build: 
    needs: code
    runs-on: ubuntu-22.04
    steps:
      - name: Build the code with Docker  
        uses: docker/setup-buildx-action@v3 
  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: test the Application  
        run: echo "test passed" 
  # CD
  deploy:
    needs: [code,build,test]
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy app on server  
        run: echo "App Deployed" 
  




