name: Protect README

# When the workflow runs
on:
  #push:
    #branches: [main]

  #pull_request:
    #paths:
      #- README.md
      #- .github/workflows/README.md
  workflow_dispatch:


# What the workflow does
jobs:

  # First job
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Tell hello
        run: echo "Hello Friend"

  # Second job
  repo-name:
    needs: greet
    runs-on: ubuntu-latest

    steps:
      - name: Show Repo name
        run: echo "The repo name is ${{ github.event.repository.name }}"

  # README protection
  protect-readme:
    # Only run this job for pull requests
    if: github.event_name == 'pull_request'

    needs: repo-name
    runs-on: ubuntu-latest

    steps:
      - name: Reject README changes
        run: |
          echo "Changes to README.md are not allowed."
          exit 1
